package com.example.scholateacher.Model

class AssignCourse(
    var id: String?=null,
    var section_id: String?=null,
    var course_id: String?=null,
    var teacher_id: String?=null,
    var credit: String?=null,
    var total_class: Int?=null,
    var date1: String?=null,
    var date2: String?=null,
    var date3: String?=null,
    var date4: String?=null,
    var date5: String?=null,
    var date6: String?=null,
    var date7: String?=null,
    var date8: String?=null,
    var date9: String?=null,
    var date10: String?=null,
    var date11: String?=null,
    var date12: String?=null,
    var date13: String?=null,
    var date14: String?=null,
    var date15: String?=null,
    var date16: String?=null,
    var date17: String?=null,
    var date18: String?=null,
    var date19: String?=null,
    var date20: String?=null,
    var date21: String?=null,
    var date22: String?=null,
    var date23: String?=null,
    var date24: String?=null,
    var date25: String?=null,
    var date26: String?=null,
    var date27: String?=null,
    var date28: String?=null,
    var date29: String?=null,
    var date30: String?=null,
    var date31: String?=null,
    var date32: String?=null,
    var date33: String?=null,
    var date34: String?=null,
    var date35: String?=null,
    var date36: String?=null,
    var date37: String?=null,
    var date38: String?=null,
    var date39: String?=null,
    var date40: String?=null,
    var date41: String?=null,
    var date42: String?=null
    ) {
}