package com.example.scholateacher.Model

class TheoryAttendance(
    var id: String?=null,
    var assignCourseId: String?=null,
    var studentId: String?=null,
    var class1: String?=null,
    var class2: String?=null,
    var class3: String?=null,
    var class4: String?=null,
    var class5: String?=null,
    var class6: String?=null,
    var class7: String?=null,
    var class8: String?=null,
    var class9: String?=null,
    var class10: String?=null,
    var class11: String?=null,
    var class12: String?=null,
    var class13: String?=null,
    var class14: String?=null,
    var class15: String?=null,
    var class16: String?=null,
    var class17: String?=null,
    var class18: String?=null,
    var class19: String?=null,
    var class20: String?=null,
    var class21: String?=null,
    var class22: String?=null,
    var class23: String?=null,
    var class24: String?=null,
    var class25: String?=null,
    var class26: String?=null,
    var class27: String?=null,
    var class28: String?=null,
    var class29: String?=null,
    var class30: String?=null,
    var class31: String?=null,
    var class32: String?=null,
    var class33: String?=null,
    var class34: String?=null,
    var class35: String?=null,
    var class36: String?=null,
    var class37: String?=null,
    var class38: String?=null,
    var class39: String?=null,
    var class40: String?=null,
    var class41: String?=null,
    var class42: String?=null
) {
}